import numpy as np
import time
import itertools

def max_l1_zonotope(vectors):
    """
    Maximize ||x||_1 over Zonotope Z = {x | x = sum(a_i * v_i), |a_i| <= 1}.
    Since ||x||_1 = max_{s in {-1,1}^d} s^T x, and max_{x in Z} s^T x = sum(|s_j * v_{i,j}|),
    we need max_s sum_i |s^T v_i|.
    For small d, brute force s is 2^d. The review suggests this is polynomially easy (e.g., via LP).
    Here we use the property that max ||x||_1 = max_{S subset of vertices} ... actually simpler:
    max_{x in Z} ||x||_1 = max_{u in {-1, 1}^d} max_{x in Z} u^T x = max_{u in {-1, 1}^d} sum_{i=1}^m |u^T v_i|.
    This is a max over 2^d terms. If d is small, this is fast.
    """
    d = vectors.shape[1]
    if d == 0:
        return 0.0
    
    max_val = 0.0
    # Iterate over all 2^d sign vectors u
    # For larger d, this becomes expensive, but typically d < m in these examples.
    # To strictly adhere to "polynomially easy" intuition vs L2's "exponential in m",
    # we note that L1 complexity is 2^d and L2 complexity is 2^m.
    for u in itertools.product([1, -1], repeat=d):
        u_vec = np.array(u)
        # Compute sum_i |u^T v_i|
        dot_prods = vectors @ u_vec
        current_sum = np.sum(np.abs(dot_prods))
        if current_sum > max_val:
            max_val = current_sum
    return max_val

def max_linf_zonotope(vectors):
    """
    Maximize ||x||_infinity over Zonotope.
    max ||x||_inf = max_j max_x |x_j|.
    x_j = sum_i a_i v_{i,j}. max_{|a_i|<=1} |sum a_i v_{i,j}| = sum_i |v_{i,j}|.
    So max_j sum_i |v_{i,j}|.
    This is O(m*d), which is linear/polynomial.
    """
    if vectors.size == 0:
        return 0.0
    # sum of absolute values per column (dimension)
    sums_per_dim = np.sum(np.abs(vectors), axis=0)
    return np.max(sums_per_dim)

def max_l2_zonotope_bruteforce(vectors):
    """
    Maximize ||x||_2 over Zonotope vertices.
    The maximum of a convex function over a convex polytope occurs at a vertex.
    Vertices of the zonotope generated by v_i are sum_{i=1}^m a_i v_i with a_i in {-1, 1}.
    Note: Not all combinations are vertices if vectors are linearly dependent, but for random vectors, they are.
    Checking all 2^m combinations.
    """
    m = vectors.shape[0]
    if m == 0:
        return 0.0
    
    max_val = 0.0
    # Generate all 2^m combinations of signs
    # Using itertools.product for clarity
    for signs in itertools.product([1, -1], repeat=m):
        signs_vec = np.array(signs)
        x = signs_vec @ vectors
        norm = np.linalg.norm(x)
        if norm > max_val:
            max_val = norm
    return max_val

def main():
    np.random.seed(42)
    d = 3  # Dimension
    
    # List of m values to test. 
    # m=20 is 1,048,576 vertices. 
    # m=30 is 1,073,741,824 vertices, which might take a bit longer in Python but should be runnable within a reasonable time (few seconds) if optimized, 
    # but the brute force loop in pure Python might be slow.
    # Let's stick to m=3, 5, 10, 15, 20 to ensure it runs quickly.
    # The review shows up to 30, but 20 is often sufficient to show the trend.
    # Let's include 20. 1M iterations in Python is ~1-2 seconds.
    
    m_values = [3, 5, 10, 15, 20]
    
    print(f"{'m':>4} | {'Num Vertices':>14} | {'L1 Max (2^d)':>12} | {'Linf Max':>12} | {'L2 Max (Brute)':>12} | {'L1 Time(ms)':>11} | {'Linf Time(ms)':>11} | {'L2 Time(ms)':>11}")
    print("-" * 100)
    
    for m in m_values:
        # Generate random vectors
        vectors = np.random.randn(m, d)
        
        num_vertices = 2 ** m
        
        # L1 Calculation
        start_time = time.time()
        l1_max = max_l1_zonotope(vectors)
        l1_time = (time.time() - start_time) * 1000
        
        # Linf Calculation
        start_time = time.time()
        linf_max = max_linf_zonotope(vectors)
        linf_time = (time.time() - start_time) * 1000
        
        # L2 Calculation
        start_time = time.time()
        l2_max = max_l2_zonotope_bruteforce(vectors)
        l2_time = (time.time() - start_time) * 1000
        
        print(f"{m:>4} | {num_vertices:>14,} | {l1_max:>12.4f} | {linf_max:>12.4f} | {l2_max:>12.4f} | {l1_time:>11.2f} | {linf_time:>11.2f} | {l2_time:>11.2f}")

if __name__ == "__main__":
    main()
